import { ATLAS_ART, ATLAS_SCALE, GROUND_Y } from './physics.js';

/**
 * Atlas is a piece of vector art, not code: assets/atlas.svg, generated by
 * scripts/make-atlas-art.mjs. Everything here does is place it.
 *
 * The one rule: the artwork's support line — the flat across both hands and his
 * upper back — is scaled and positioned to land exactly on y = 0 spanning the
 * platform's full width, which is the top surface of the static platform body.
 */

const INK = '#17181a';

/** @typedef {{ ground: string, groundShade: string }} AtlasStyle */

const ART_URL = new URL('../assets/atlas.svg', import.meta.url).href;

/** Where the artwork lands in world units, derived from its own metrics. */
const DRAW = {
  x: (0 - (ATLAS_ART.supportLeft + ATLAS_ART.supportRight) / 2) * ATLAS_SCALE,
  y: -ATLAS_ART.supportY * ATLAS_SCALE,
  w: ATLAS_ART.view.w * ATLAS_SCALE,
  h: ATLAS_ART.view.h * ATLAS_SCALE,
};

/** Head position in world units, so sweat runs off the right place. */
const HEAD_Y = (280 - ATLAS_ART.supportY) * ATLAS_SCALE;

/** @type {HTMLImageElement | null} */
let art = null;
void loadArt();

async function loadArt() {
  try {
    const img = new Image();
    img.decoding = 'async';
    await new Promise((resolve, reject) => {
      img.onload = () => resolve(undefined);
      img.onerror = () => reject(new Error('could not load assets/atlas.svg'));
      img.src = ART_URL;
    });
    if (img.decode) await img.decode().catch(() => undefined);
    art = img;
  } catch {
    // The ground still draws; the game is playable without him on screen.
  }
}

/**
 * @typedef {object} AtlasOptions
 * @property {number} strain 0 = fresh and confident, 1 = holding up a solar system.
 * @property {number} time   Seconds since the run began, for the tremble.
 * @property {number} scale  Camera scale, so the ground line keeps a sane thickness.
 * @property {AtlasStyle} style
 */

/**
 * @param {CanvasRenderingContext2D} ctx
 * @param {AtlasOptions} opts
 */
export function drawAtlas(ctx, opts) {
  const { strain, time, scale, style } = opts;

  drawGround(ctx, style, Math.max(4, 1.8 / scale));
  if (!art) return;

  ctx.save();
  // He wobbles harder the more absurd the pile gets.
  const wobble = strain * 2.8;
  ctx.translate(Math.sin(time * 21) * wobble, Math.sin(time * 16.5 + 1.1) * wobble * 0.55);

  ctx.drawImage(art, DRAW.x, DRAW.y, DRAW.w, DRAW.h);
  if (strain > 0.3) drawEffort(ctx, strain, time, scale);

  ctx.restore();
}

/**
 * @param {CanvasRenderingContext2D} ctx
 * @param {AtlasStyle} style
 * @param {number} ink
 */
function drawGround(ctx, style, ink) {
  const reach = 24000;
  ctx.fillStyle = style.ground;
  ctx.fillRect(-reach, GROUND_Y, reach * 2, reach);
  ctx.fillStyle = style.groundShade;
  ctx.fillRect(-reach, GROUND_Y, reach * 2, 8);
  ctx.strokeStyle = INK;
  ctx.lineWidth = ink;
  ctx.beginPath();
  ctx.moveTo(-reach, GROUND_Y);
  ctx.lineTo(reach, GROUND_Y);
  ctx.stroke();
}

/**
 * Sweat off the temples. The artwork has no face — like the reference it came
 * from — so this and the tremble are what carry how hard he is working.
 * @param {CanvasRenderingContext2D} ctx
 * @param {number} strain
 * @param {number} time
 * @param {number} scale
 */
function drawEffort(ctx, strain, time, scale) {
  ctx.strokeStyle = '#4f93cc';
  ctx.fillStyle = '#a9dcf7';
  ctx.lineWidth = Math.max(2.5, 1.2 / scale);
  ctx.lineJoin = 'round';

  const beads = strain > 0.7 ? 3 : 2;
  for (let i = 0; i < beads; i++) {
    const phase = (time * 0.7 + i * 0.41) % 1;
    const side = i % 2 === 0 ? -1 : 1;
    const x = side * (52 + phase * 30);
    const y = HEAD_Y - 26 + phase * 96;
    ctx.globalAlpha = Math.sin(phase * Math.PI) * 0.95;
    // Angular droplet, to match the artwork.
    ctx.beginPath();
    ctx.moveTo(x, y - 12);
    ctx.lineTo(x + 8, y + 2);
    ctx.lineTo(x, y + 10);
    ctx.lineTo(x - 8, y + 2);
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
  }
  ctx.globalAlpha = 1;
}
